### PR TITLE
Introduce Truffleruby 24.2.0 EA Build 05

### PR DESCRIPTION
**Pull request by ZynoZin**
- [x]  Review draft release
- [x]  Publish release
- [x]  Run checks

### CODE REVIEW

**Review by brahimhaddou — APPROVED** [review]
LGTM

**Comment by nirvdrum** [comment]
Should this have updated the _latest-ea.json_ file and the various _latest-*.url_ files? Since I've been curling those files, my systems are still installing b04. It's quite convenient having the latest URLs available in a something I can easily `curl` and pipe the URL into another process.

**Comment by ezzarghili** [comment]
> Should this have updated the _latest-ea.json_ file and the various _latest-*.url_ files? Since I've been curling those files, my systems are still installing b04. It's quite convenient having the latest URLs available in a something I can easily `curl` and pipe the URL into another process.

Thanks for the report, @ZynoZin please investigate what happened here and create a fix PR

**Comment by ZynoZin** [comment]
> Should this have updated the _latest-ea.json_ file and the various _latest-*.url_ files? Since I've been curling those files, my systems are still installing b04. It's quite convenient having the latest URLs available in a something I can easily `curl` and pipe the URL into another process.

@nirvdrum Thanks for mentioning that, I have made a PR fix for this, will be merged shortly - https://github.com/graalvm/graal-languages-ea-builds/pull/111

**Pull request merged**
